/**
 * pdfImage.js
 *
 * Image plumbing for the hand-rolled PDF writer in purePdfBuilder.js.
 *
 * A PDF cannot read a PNG file directly, and React Native has no built-in
 * way to read an asset as base64 at runtime, so the brand artwork is baked
 * into src/assets/billBrandImages.js (generated by
 * `npm run build:bill-assets`) as a zlib stream per image. The only thing
 * left to do on the device is turn that base64 string back into bytes and
 * hand them to the writer — no compressor, no decoder, no native module.
 */

const BASE64_ALPHABET =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

const sextet = (str, index) => BASE64_ALPHABET.indexOf(str[index]);

/**
 * Decodes base64 into a "binary string": a JS string where each character
 * is one byte (charCode 0-255).
 *
 * That representation is deliberate. The PDF writer concatenates strings
 * and finally runs everything through its own base64 encoder, so a string
 * whose charCodes are already the raw bytes survives the round trip
 * untouched, and `binaryString.length` is exactly the stream's /Length in
 * bytes.
 */
export const base64ToBinaryString = base64 => {
  const clean = String(base64 || '').replace(/[^A-Za-z0-9+/]/g, '');
  const bytes = [];

  for (let i = 0; i < clean.length; i += 4) {
    const quad =
      (sextet(clean, i) << 18) |
      (sextet(clean, i + 1) << 12) |
      (sextet(clean, i + 2) << 6) |
      sextet(clean, i + 3);

    bytes.push((quad >> 16) & 0xff);
    if (clean.length > i + 2) {
      bytes.push((quad >> 8) & 0xff);
    }
    if (clean.length > i + 3) {
      bytes.push(quad & 0xff);
    }
  }

  // String.fromCharCode(...bytes) can blow the argument limit on large
  // payloads, so build it in chunks.
  let result = '';
  for (let i = 0; i < bytes.length; i += 4096) {
    result += String.fromCharCode.apply(null, bytes.slice(i, i + 4096));
  }
  return result;
};

export default base64ToBinaryString;
